server:
  port: ${SERVICE_PORT:7001}
  
elasticsearch:
  clustername: elasticsearch
  #host: <aws-elastic-search-service-url>
  host: http://localhost:9200
  indexName: employee_index

#Datasource configuration
spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
    properties:
      hibernate:
         jdbc:
            batch_size: 20
         order_inserts: true 
    
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: ${DATABASE_URL:jdbc:oracle:thin:@localhost:1521:XE}
    username: EMPLOYEE_ES
    password: test1234
    
#Liquibase Configuration
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  data:
    elasticsearch:
      properties:
        index:
          search:
            slowlog:
              threshold:
                query:
                  info: 1ms
       
security:
  ignored:
    - /swagger-ui.html
    - /webjars/**
    - /swagger-resources/**
    - /images/**
    - /css/**
    - /v2/**
    - /actuator/**

      
logging:
   level:
      org:
         springframework:
            web: INFO
            data:
              elasticsearch:
                core: DEBUG
                index:
                  search:
                    showlog:
                      query: INFO
         hibernate: INFO