server:
  port: ${SERVICE_PORT:7001}
  
elasticsearch:
  clustername: elasticsearch
  host: localhost
  port: 9200

#Datasource configuration
spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
    properties:
      hibernate:
         jdbc:
            batch_size: 20
         order_inserts: true 
    
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: ${DATABASE_URL:jdbc:oracle:thin:@localhost:1521:XE}
    username: EMP_MANAGEMENT
    password: emp1234
    
#Liquibase Configuration
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

security:
  ignored:
    - /swagger-ui.html
    - /webjars/**
    - /swagger-resources/**
    - /images/**
    - /css/**
    - /v2/**
    - /actuator/**

      
logging:
   level:
      org:
         springframework:
            web: INFO
            data:
              elasticsearch:
                core: DEBUG
         hibernate: INFO
        
